---
# spell-checker: disable
apiVersion: "cert-manager.io/v1"
kind: "Certificate"
metadata:
  name: "internal-k8s-ca"
spec:
  secretName: "internal-k8s-ca-tls"  # pragma: allowlist secret
  duration: "2160h"  # 90d
  subject:
    organizations:
      - "Nautobot"
  commonName: "ca.cluster.local"
  isCA: true
  privateKey:
    algorithm: "RSA"
    encoding: "PKCS1"
    size: 4096
  usages:
    - "server auth"
    - "client auth"
  dnsNames:
    - "ca.cluster.local"
  issuerRef:
    name: "selfsigned-issuer"
---
apiVersion: "cert-manager.io/v1"
kind: "Issuer"
metadata:
  name: "selfsigned-issuer"
spec:
  selfSigned: {}
---
apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "internal-k8s-ca"
spec:
  ca:
    secretName: "internal-k8s-ca-tls"  # pragma: allowlist secret
