---
# spell-checker: disable
dev_addr: "0.0.0.0:8001"
site_name: "Nautobot Helm Charts"
# site_url: "https://tbd.example.com"
# repo_url: "https://github.com/org/example"
# edit_uri: "edit/main/docs"
copyright: "Copyright &copy; Network To Code"
theme:
  name: "material"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "navigation.tracking"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.indexes"
    - "search.suggest"
    - "search.highlight"
    - "search.share"
  favicon: "assets/favicon.png"
  logo: "assets/logo.png"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
extra_css:
  - "assets/extra.css"

extra:
  generator: true

markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "footnotes"
plugins:
  - "search"
  - "mkdocs-version-annotations"

nav:
  - Overview: "index.md"
  - Installation:
    - Basic Installation: "installation/basic.md"  # yamllint disable-line rule:indentation
    - Production Installation: "installation/production.md"
    - Dependencies: "installation/dependencies.md"
    - Prerequisites: "installation/prerequisites.md"
    - System Requirements: "installation/system-requirements.md"
  - Advanced Usage:
    - Topic1: "advanced-features/index.md"  # yamllint disable-line rule:indentation
