---
annotations:
  category: "Infrastructure"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: nautobot
      image: ghcr.io/nautobot/nautobot:1.5.9-py3.10
  artifacthub.io/links: |
    - name: Nautobot Documentation
      url: https://nautobot.readthedocs.io/en/stable/
    - name: Nautobot
      url: https://github.com/nautobot/nautobot
  artifacthub.io/screenshots: |
    - title: Main Page
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/screenshot1.png
    - title: Rack Elevation
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/screenshot2.png
    - title: Prefix hierarchy
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/screenshot3.png
  artifacthub.io/changes: |
    - kind: changed
      description: Upgraded Nautobot from 1.4.5 to 1.5.9
    - kind: changed
      description: Chart dependencies now included locally as they no longer exist at bitnami.com (too old)
    - kind: fixed
      description: Fixed #214 allowing sops in helm values
apiVersion: "v2"
appVersion: "1.5.9"
dependencies:
  - condition: "redis.enabled"
    name: "redis"
    repository: "file://charts/redis"
    version: "16.10.1"
  - condition: "postgresql.enabled"
    name: "postgresql"
    repository: "file://charts/postgresql"
    version: "10.16.2"
  - condition: "postgresqlha.enabled"
    name: "postgresql-ha"
    repository: "file://charts/postgresql-ha"
    version: "8.6.13"
    alias: "postgresqlha"
  - condition: "mariadb.enabled"
    name: "mariadb"
    repository: "file://charts/mariadb"
    version: "10.5.1"
  - name: "common"
    repository: "file://charts/common"
    tags:
      - "bitnami-common"
    version: "1.14.1"
description: "Nautobot is a Network Source of Truth and Network Automation Platform."
engine: "gotpl"
home: "https://github.com/nautobot/nautobot"
icon: "https://raw.githubusercontent.com/nautobot/helm-charts/main/images/NautobotLogoSquare.png"
keywords:
  - "DCIM"
  - "IPAM"
  - "SOT"
maintainers:
  - email: "opensource@networktocode.com"
    name: "Network to Code"
    url: "https://www.networktocode.com/"
name: "nautobot"
sources:
  - "https://github.com/nautobot/nautobot"
  - "https://github.com/nautobot/helm-charts"
version: "1.3.14"
