---
annotations:
  category: "Infrastructure"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/prerelease: "true"
  artifacthub.io/images: |
    - name: nautobot
      image: ghcr.io/nautobot/nautobot:1.5.15-py3.10
  artifacthub.io/links: |
    - name: Nautobot Documentation
      url: https://nautobot.readthedocs.io/en/stable/
    - name: Nautobot
      url: https://github.com/nautobot/nautobot
  artifacthub.io/screenshots: |
    - title: Main Page
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_main_page.png
    - title: Config Contexts
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_config_contexts.png
    - title: GraphQL
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_graphiql.png
    - title: Prefix hierarchy
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_prefix_hierarchy.png
    - title: Config Compliance
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_plugin_golden_config.png
    - title: Chatops
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_plugin_chatops.png
  # TODO CHANGE THIS
  artifacthub.io/changes: |
    - kind: added
      description: Added NGINX sidecars
    - kind: added
      description: Added NGINX and uWSGI exporter sidecars for metrics
    - kind: added
      description: Added the ability to add separate endpoints such as /api and /graphql for scaling out
    - kind: added
      description: Added the ability to add deploy workers for [additional queues](https://docs.nautobot.com/projects/core/en/stable/administration/celery-queues)
    - kind: added
      description: Added the ability to [host static files separately](https://docs.nautobot.com/projects/core/en/stable/advanced-features/static-only).
    - kind: added
      description: Added the ability to [initialize Nautobot as a Job](https://docs.nautobot.com/projects/core/en/stable/advanced-features/init-hook).
    - kind: changed
      description: Upgraded Nautobot from 1.4.5 to 1.5.15
    - kind: changed
      description: Chart dependencies now included locally as they no longer exist at bitnami.com (too old)
    - kind: fixed
      description: Fixed #214 allowing sops in helm values
    - kind: deprecated
      description: The `.celeryWorker` and `.celeryBeat` values have been deprecated and are now defined in `.workers.default` and `.workers.beat`
apiVersion: "v2"
appVersion: "1.5.15"
version: "2.0.0-alpha.10"
dependencies:
  - condition: "redis.enabled"
    name: "redis"
    repository: "https://charts.bitnami.com/bitnami"
    version: "17.x.x"
  - condition: "postgresql.enabled"
    name: "postgresql"
    repository: "https://charts.bitnami.com/bitnami"
    version: "12.x.x"
  - condition: "postgresqlha.enabled"
    name: "postgresql-ha"
    repository: "https://charts.bitnami.com/bitnami"
    version: "11.x.x"
    alias: "postgresqlha"
  - condition: "mariadb.enabled"
    name: "mariadb"
    repository: "https://charts.bitnami.com/bitnami"
    version: "11.x.x"
  - name: "common"
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - "bitnami-common"
    version: "2.x.x"
description: "Nautobot is a Network Source of Truth and Network Automation Platform."
home: "https://github.com/nautobot/nautobot"
icon: "https://raw.githubusercontent.com/nautobot/helm-charts/main/images/NautobotLogoSquare.png"
keywords:
  - "DCIM"
  - "IPAM"
  - "SOT"
maintainers:
  - email: "opensource@networktocode.com"
    name: "Network to Code"
    url: "https://www.networktocode.com/"
name: "nautobot"
sources:
  - "https://github.com/nautobot/nautobot"
  - "https://github.com/nautobot/helm-charts"
