---
postgresql:
  enabled: false

redis:
  architecture: "replication"
  sentinel:
    enabled: true
    masterSet: "nautobot"
  auth:
    password: "change-me"

ingress:
  enabled: true
  path: "/*"

metrics:
  enabled: true
  capacityMetrics:
    enabled: true
  prometheusRule:
    enabled: true

commonAnnotations:
  annotate_everything: "everywhere"
serviceAccount:
  annotations:
    service_account_annotation: "only_the_sa"

mariadb:
  enabled: false

postgresqlha:
  postgresql:
    password: "change-me"
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
