---
nautobot:
  apiEndpoint:
    enabled: true
  pdb:
    create: true
  extraVolumeMounts:
    - name: "gmail-auth"
      mountPath: "/opt/nautobot/circuit-maintenance-secrets"
      readOnly: true
  extraVolumes:
    - name: "gmail-auth"
      secret:
        secretName: "nautobot-gmail-auth"
  nginx:
    enabled: true

nautobots:
  # Enable a separate deployment specifically for API requests
  api:
    enabled: true
    ingressPath: "/api"
    replicaCount: 3
    autoscaling:
      enabled: false

  # Enable a separate deployment specifically for GraphQL requests
  graphql:
    enabled: true
    ingressPath: "/graphql"

celeryBeat:
  extraVolumeMounts:
    - name: "gmail-auth"
      mountPath: "/opt/nautobot/circuit-maintenance-secrets"
      readOnly: true
  extraVolumes:
    - name: "gmail-auth"
      secret:
        secretName: "nautobot-gmail-auth"

celeryWorker:
  autoscaling:
    enabled: true
  extraVolumeMounts:
    - name: "gmail-auth"
      mountPath: "/opt/nautobot/circuit-maintenance-secrets"
      readOnly: true
  extraVolumes:
    - name: "gmail-auth"
      secret:
        secretName: "nautobot-gmail-auth"
  pdb:
    create: true

postgresql:
  auth:
    password: "change-me"
redis:
  auth:
    password: "change-me"

ingress:
  enabled: true
  ingressClassName: "nginx"
  path: "/*"

metrics:
  enabled: true
  capacityMetrics:
    enabled: true
  nginxExporter:
    enabled: true
  uwsgiExporter:
    enabled: true
  prometheusRule:
    enabled: true

commonAnnotations:
  annotateeverything: "everywhere"
serviceAccount:
  annotations:
    saannotation: "only_the_sa"
