---
nautobot:
  autoscaling:
    enabled: true

celery:
  autoscaling:
    enabled: true

postgresql:
  enabled: false
redis:
  auth:
    password: "change-me"

ingress:
  enabled: true
  path: "/*"

metrics:
  enabled: true
  capacityMetrics:
    enabled: true
  prometheusRule:
    enabled: true

commonAnnotations:
  annotate_everything: "everywhere"
serviceAccount:
  annotations:
    service_account_annotation: "only_the_sa"

mariadb:
  enabled: true
  auth:
    password: "change-me"
