---
nautobot:
  singleInit: true

postgresql:
  enabled: false

redis:
  architecture: "replication"
  sentinel:
    enabled: true
    masterSet: "nautobot"
  auth:
    password: "change-me"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

postgresqlha:
  postgresql:
    password: "change-me"
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
