---
nautobot:
  pdb:
    create: true
  extraVolumeMounts:
    - name: "gmail-auth"
      mountPath: "/opt/nautobot/circuit-maintenance-secrets"
      readOnly: true
  extraVolumes:
    - name: "gmail-auth"
      secret:
        secretName: "nautobot-gmail-auth"
  nginx:
    enabled: true

nautobots:
  # Enable a separate deployment specifically for API requests
  api:
    enabled: true
    ingressPath: "/api"
    initNautobot: false
    replicaCount: 3
    autoscaling:
      enabled: false

  # Enable a separate deployment specifically for GraphQL requests
  graphql:
    enabled: true
    initNautobot: false
    ingressPath: "/graphql"
    autoscaling:
      enabled: true

workers:
  beat:
    extraVolumeMounts:
      - name: "gmail-auth"
        mountPath: "/opt/nautobot/circuit-maintenance-secrets"
        readOnly: true
    extraVolumes:
      - name: "gmail-auth"
        secret:
          secretName: "nautobot-gmail-auth"

celery:
  autoscaling:
    enabled: true
  extraVolumeMounts:
    - name: "gmail-auth"
      mountPath: "/opt/nautobot/circuit-maintenance-secrets"
      readOnly: true
  extraVolumes:
    - name: "gmail-auth"
      secret:
        secretName: "nautobot-gmail-auth"
  pdb:
    create: true

ingress:
  enabled: true
  ingressClassName: "nginx"
  path: "/*"
  extraHosts:
    - hostname: "nautobot2.local"
      path: "/"
      pathType: "Prefix"
      extraPaths: []
      backendProtocol: "https"
  tls: true

metrics:
  enabled: true
  capacityMetrics:
    enabled: true
  nginxExporter:
    enabled: true
  uwsgiExporter:
    enabled: true
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true

commonAnnotations:
  annotate_everything: "everywhere"
serviceAccount:
  annotations:
    service_account_annotation: "only_the_sa"
